src/main/java/com/control/back/halo/bookmark/entity/Category.java
package com.control.back.halo.bookmark.entity;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.commons.lang3.StringUtils;

import com.alibaba.fastjson.annotation.JSONField;
import com.control.back.halo.basic.entity.BaseEntity;

@Entity
@Table(name = "halo_category")
public class Category extends BaseEntity {

    /**
     */
    private static final long serialVersionUID = -5123091774594274385L;

    /**
     * name,parent_id,add_date,last_modifed
     */

    String title;

    Long dateAdded;
    Long dateGroupModified;

    @ManyToOne(fetch = FetchType.LAZY, cascade = { CascadeType.MERGE, CascadeType.PERSIST })
    Category parent;

    @OneToMany(mappedBy = "parent", fetch = FetchType.LAZY)
    List<Category> children;

    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY)
    List<Mark> marks;

    @Column
    private Integer titleHashCode;

    public Integer getTitleHashCode() {
        return titleHashCode;
    }

    public void setTitleHashCode(Integer titleHashCode) {
        this.titleHashCode = titleHashCode;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(Long dateAdded) {
        this.dateAdded = dateAdded;
    }

    public Long getDateGroupModified() {
        return dateGroupModified;
    }

    public void setDateGroupModified(Long dateGroupModified) {
        this.dateGroupModified = dateGroupModified;
    }

    public void setParent(Category parent) {
        this.parent = parent;
    }

    public void setChildren(List<Category> children) {
        this.children = children;
    }

    @JSONField(serialize = false)
    public Category getParent() {
        return parent;
    }

    public String getParentTitle() {
        if (parent != null) {
            return parent.getTitle();
        }
        return null;
    }

    @JSONField(serialize = false)
    public List<Category> getChildren() {
        return children;
    }

    @JSONField(serialize = false)
    public List<Mark> getMarks() {
        return marks;
    }

    public void setMarks(List<Mark> marks) {
        this.marks = marks;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((parent == null) ? 0 : parent.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (getClass() != obj.getClass())
            return false;
        Category other = (Category) obj;
        if (parent != null && other.parent != null) {
            if (!StringUtils.equals(parent.getTitle(), other.parent.getTitle())) {
                return false;
            }
        } else if (other.parent == null && parent == null) {
        } else {
            return false;
        }

        if (!StringUtils.equals(title, other.title)) {
            return false;
        }
        return true;
    }
}

src/main/java/com/control/back/halo/bookmark/controller/CategoryController.java
package com.control.back.halo.bookmark.controller;

import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.control.back.halo.basic.controller.BaseController;
import com.control.back.halo.basic.entity.vo.TreeNode;
import com.control.back.halo.basic.json.Result;
import com.control.back.halo.basic.log4j.Logger;
import com.control.back.halo.bookmark.entity.Category;
import com.control.back.halo.bookmark.http.HttpRequest;
import com.control.back.halo.bookmark.json.Response;
import com.control.back.halo.bookmark.service.ICategoryService;
import com.control.back.halo.bookmark.service.IURLService;

@Controller
@RequestMapping("/category")
public class CategoryController extends BaseController {

    private static Logger    logger = Logger.getLogger(CategoryController.class);

    @Autowired
    private ICategoryService categorySerivce;

    @Autowired
    private IURLService      urlService;

    @RequestMapping(value = "/isConnection.json", produces = "application/json")
    public @ResponseBody Result isConnection(String urlAddress) {
        Result r = new Result();
        boolean flag = urlService.exists(urlAddress);
        r.setSuccess(flag);
        return r;
    }

    @RequestMapping(value = "/loadCategoryTree.json", produces = "application/json")
    public @ResponseBody List<TreeNode> loadCategoryTree() {
        return categorySerivce.loadCategoryTree();
    }

    @RequestMapping(value = "/insert.json", produces = "application/json")
    public @ResponseBody String insert(Category category) {
        try {
            categorySerivce.save(category);
        } catch (Exception e) {
            return "error";
        }
        return "success";
    }

    @RequestMapping(value = "/bookmarks.json", produces = "application/json")
    public @ResponseBody Result findBookmarks(Long parentId) {
        Result r = null;
        try {
            Category category = categorySerivce.find(parentId);
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("rootCategory", category);
            params.put("childs", category.getChildren());
            params.put("bookmarks", category.getMarks());
            r = new Result(true, "success", params);
        } catch (Exception ee) {
            r = Result.error("error:" + ee.getLocalizedMessage());
        }
        return r;
    }

    @RequestMapping("/index")
    public ModelAndView index() {
        return new ModelAndView("/category/index");
    }

    @RequestMapping("/repeatCategory")
    public String repeatCategory(Model model) {
        model.addAttribute("repeatCategorys", categorySerivce.findRepeatCategory());
        return "/category/repeatCategory";
    }

    @RequestMapping("/mergeCategory.json")
    public @ResponseBody Result mergeCategory(Long mId, String cIds) {
        boolean flag = categorySerivce.mergeCategory(mId, cIds);
        return new Result(flag, "merge", flag);
    }

    @RequestMapping("/rename.json")
    public @ResponseBody Result rename(Long id, String title, Long pid) {
        try {
            Category category = categorySerivce.find(id);
            if (category == null) {
                category = new Category();
                category.setParent(categorySerivce.find(pid));
            }
            category.setTitle(title);
            category.setTitleHashCode(title.trim().hashCode());
            category = categorySerivce.update(category);
            return new Result(true, "rename success", category.getId());
        } catch (Exception e) {
            logger.error("rename is error params [id:%s,title:%s,pid:%s]", e, id, title, pid);
        }
        return Result.error("error");
    }

    @RequestMapping("/onDrop.json")
    public @ResponseBody Result onDrop(String moveIds, Long parentId) {
        if (StringUtils.isNotBlank(moveIds)) {
            List<Category> categorys = categorySerivce.findCategoryByIds(moveIds);
            Category parent = categorySerivce.find(parentId);
            for (Iterator<Category> iterator = categorys.iterator(); iterator.hasNext();) {
                Category category = iterator.next();
                category.setParent(parent);
                categorySerivce.update(category);
            }
            return Result.success("drop success");

        }
        return Result.error("drop error");
    }

    @RequestMapping("/remove.json")
    public @ResponseBody Result remove(Long id) {
        Category category = categorySerivce.find(id);

        if (category == null) { return Result.success("删除成功!"); }

        if (category.getChildren() != null && !category.getChildren().isEmpty()) { return new Result(false, "分类下面存在子分类不允许删除!", null); }

        if (category.getMarks() != null && !category.getMarks().isEmpty()) { return new Result(false, "分类下面存在书签不允许删除!", null); }

        categorySerivce.delete(category);
        return Result.success("删除成功!");
    }

    @RequestMapping("/findCategoryByName.json")
    public @ResponseBody Response findCategoryByName(String q) {
        try {
            List<Category> categorys = categorySerivce.findCategoryByName(q);
            return new Response(true, "success", categorys);
        } catch (Exception e) {
            logger.error("find category error,params[name:%s]", e, q);
            return Response.error("error");
        }
    }

    @RequestMapping("/relChart")
    public String relChart() {
        return "/category/relChart";
    }

    @RequestMapping("/relChart/npm.json")
    public @ResponseBody JSONObject relNpm() {
        String jsonStr = HttpRequest.sendGet("http://echarts.baidu.com/data/asset/data/npmdepgraph.min10.json", null);
        JSONObject jsonObj = JSON.parseObject(jsonStr);
        return jsonObj;
    }
}

src/main/resources/templates/category/index.ftl
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<title> halo bookmark</title>
<link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
<link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0" rel="stylesheet">
<link href="//cdn.bootcss.com/zTree.v3/3.5.24/css/zTreeStyle/zTreeStyle.css" rel="stylesheet">
<link href="/js/plugins/bootstrap-fileinput/css/fileinput.css" rel="stylesheet">
<link href="//cdn.bootcss.com/select2/4.0.3/css/select2.css" rel="stylesheet">
<script>
	var _baseurl = "http://127.0.0.1";
</script>

<style>
.ellipsis {
	overflow: hidden;
	white-space: nowrap;
	text-overflow: ellipsis;
}

.table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
	border-bottom-width: 1px;
}

.pagination {
	margin: 0;
}

.ztree li span.button.add {
	margin-left: 2px;
	margin-right: -1px;
	background-position: -144px 0;
	vertical-align: top;
	*vertical-align: middle
}
</style>
</head>

<body class="gray-bg">
	<div class="row wrapper border-bottom white-bg page-heading">
		<div class="col-lg-10">
			<h2>书签管理</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">主页</a></li>
				<li><a>书签管理</a></li>
			</ol>
		</div>
		<div class="col-lg-2"></div>
	</div>

	<div class="wrapper wrapper-content animated fadeInRight">
		<div class="row">
			<div class="col-sm-12">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5>书签管理</h5>
					</div>
					<div class="ibox-content">
						<div class="btn-group" role="group">
							<p>
							<button type="button" class="btn btn-success" data-toggle="modal"
								data-target="#importMark">
								<i class="fa fa-plus" aria-hidden="true"></i> 从html导入书签
							</button>
							<button type="button" class="btn btn-success" data-toggle="modal"
								id="repeatViewButton">
								<i class="fa fa-search" aria-hidden="true"></i> 查看重复分类
							</button>
							<button type="button" class="btn btn-success" data-toggle="modal"
								id="repeatMarkViewButton">
								<i class="fa fa-search" aria-hidden="true"></i> 查看重复书签
							</button>
							<button type="button" class="btn btn-success" data-toggle="modal"
								id="relChartViewButton">
								<i class="fa fa-search" aria-hidden="true"></i> 查看关系图
							</button>
							</p>
						</div>
						<hr>
						<div class="row">
							<div class="col-md-3">
								<div class="form-group">
									<div class="col-md-9">
										<input type="text" class="form-control" name="categoryName"
											id="categoryName" placeholder="请输入分类名称" />
									</div>
									<div class="col-md-3">
										<button type="button" id="searchCategory" class="btn btn-info">搜索</button>
									</div>
								</div>
								<div class="form-group">
									<div class="col-md-12">
										<ul id="treeDemo" class="ztree"></ul>
									</div>
								</div>
							</div>
							<div id="main" class="col-md-9">
								<div class="form-horizontal" role="form">
									<div class="form-group">
										<div class="col-md-9">
											<input type="text" name="markName" id="markName"
												placeholder="请输入查询信息" class="form-control" />
										</div>
										<div class="col-md-3">
											<button type="button" id="searchBy" class="btn">搜索</button>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12">
											<table id="markData"
												class="table table-striped table-bordered">
												<thead>
													<tr>
														<th width="75%">名称</th>
														<th width="25%">所属分类</th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td colspan="2">未查询到结果</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-7">
											<div id="bootstrapPaginator"></div>
										</div>
										<div class="col-md-5">
											<label class="col-md-3 control-label">显示数量</label>
											<div class="col-md-9">
												<select id="tpageNumber" class="form-control">
													<option value="20">20条</option>
													<option value="50">50条</option>
													<option value="100">100条</option>
													<option value="200">200条</option>
												</select>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<#include "/category/upload.ftl" />
	<div class="modal fade" id="repeatCategory" tabindex="-1" role="dialog"
		aria-hidden="true"></div>
	<div class="modal fade" id="repeatMark" tabindex="-1" role="dialog"
		aria-hidden="true"></div>
	<div class="modal fade" id="readMark" tabindex="-1" role="dialog"
		aria-hidden="true"></div>
</body>

<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script
	src="//cdn.bootcss.com/zTree.v3/3.5.24/js/jquery.ztree.all.min.js"></script>
<script src="/js/plugins/bootstrap-paginator.js"></script>
<script src="/js/plugins/eWin.js"></script>

<script src="/js/plugins/bootstrap-fileinput/js/fileinput.js"></script>
<script src="/js/plugins/bootstrap-fileinput/js/locales/zh.js"></script>

<script src="//cdn.bootcss.com/select2/4.0.3/js/select2.full.js"></script>
<script src="//cdn.bootcss.com/select2/4.0.3/js/i18n/zh-CN.js"></script>

<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="/js/pages/bookmark/index.js"></script>

<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>

</html>

src/main/resources/templates/category/readMark.ftl
<html lang="en" class="width-wide font-sentinel mode-night size-medium" dir="ltr">

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>${(article.title)!''}</title>
		<link href="${baseurl}/resources/css/article.css" rel="stylesheet">
	</head>

	<body class="article" data-user-authed="1" youdao="bind">
		<div class="container  bookmark">
			<article class="hentry">
				<header role="banner">
					<div class="entry-origin">
						<a href="${(article.url)!''}" target="_blank">
							${(article.url)!''}
						</a>
					</div>
					<h1 class="entry-title">${(article.title)!''}</h1>
					<ul class="entry-meta">
						<li>
						<#if article.publishDate??>
							<time class="updated" datetime="${(article.publishDate?string("yyyy-MM-dd HH:mm"))!''}" pubdate="">${article.publishDate?string("yyyy-MM-dd HH:mm")}</time>
						</#if>
						</li>
						<li>
							<a href="${article.url}" target="_blank">
								original
							</a>
						</li>
					</ul>
				</header>
				<section role="main">
					<span id="scroll-bullet">?</span>
					<div class="entry-content">
						<div>
							<div class="BlogContent">
								${article.content}
							</div>
						</div>
					</div>
					<section id="print-url">
						<h1>Original URL:</h1>
						<p>${article.url}</p>
					</section>
				</section>
			</article>
	</body>
</html>

src/main/resources/templates/category/readMarkView.ftl
<div class="modal-dialog" style="width:99% !important;">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title">${article.title}</h4>
		</div>
		<div class="modal-body">
			<iframe style="width: 100%;height: 100%;">
				<html lang="en" class="width-wide font-sentinel mode-night size-medium" dir="ltr">
					<head>
					    <meta charset="utf-8">
					    <meta name="viewport" content="width=device-width, initial-scale=1">
					    <title>${article.title}</title>
						<link rel="stylesheet" href="./article.css">
					</head>	
					<body class="article" data-user-authed="1" youdao="bind">
					    
					<div class="container  bookmark">
					    <article class="hentry" >
					        <header role="banner">
					            <div class="entry-origin">
					                <a href="${article.url}" id="article-url" title="View the original article" class="original-source" data-stat="rv-banner-original">
					                    ${article.url}
					                </a>
					            </div>
					            <h1 class="entry-title">${article.title}</h1>
					        </header>
					
					        <section role="main">
					            <span id="scroll-bullet">?</span>
					
					            <div class="entry-content">
					                <div>
										<div class="BlogContent">
											${article.content}
										</div>
									</div>
					            </div>
					            <section id="print-url">
					                <h1>Original URL:</h1>
					                <p>${article.url}</p>
					            </section>
					        </section>
					    </article>
					</body>
				</html>
			</iframe>
		</div>
	</div>
</div>

src/main/resources/templates/category/relChart.ftl
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<!-- 引入 ECharts 文件 -->
<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script src="/js/plugins/echarts/echarts-all.min.js"></script>

</head>
<body>
	<!-- 为 ECharts 准备一个具备大小（宽高）的 DOM -->
	<div id="main" style="width: 100%; height: 800px;"></div>
	<script type="text/javascript">
		// 基于准备好的dom，初始化echarts实例
		var myChart = echarts.init(document.getElementById('main'));

		myChart.showLoading();
		$.getJSON('relChart/npm.json', function (json) {
		    myChart.hideLoading();
		    myChart.setOption(option = {
		        title: {
		            text: 'NPM Dependencies'
		        },
		        animationDurationUpdate: 1500,
		        animationEasingUpdate: 'quinticInOut',
		        series : [
		            {
		                type: 'graph',
		                layout: 'none',
		                // progressiveThreshold: 700,
		                data: json.nodes.map(function (node) {
		                    return {
		                        x: node.x,
		                        y: node.y,
		                        id: node.id,
		                        name: node.label,
		                        symbolSize: node.size,
		                        itemStyle: {
		                            normal: {
		                                color: node.color
		                            }
		                        }
		                    };
		                }),
		                edges: json.edges.map(function (edge) {
		                    return {
		                        source: edge.sourceID,
		                        target: edge.targetID
		                    };
		                }),
		                label: {
		                    emphasis: {
		                        position: 'right',
		                        show: true
		                    }
		                },
		                roam: true,
		                focusNodeAdjacency: true,
		                lineStyle: {
		                    normal: {
		                        width: 0.5,
		                        curveness: 0.3,
		                        opacity: 0.7
		                    }
		                }
		            }
		        ]
		    }, true);
		});
	</script>
</body>
</html>

src/main/resources/templates/category/repeatCategory.ftl
<div class="modal-dialog" style="width:70% !important;">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title">重复的分类</h4>
		</div>
		<div class="modal-body">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th width="25%">名称</th>
						<th width="15%">所属分类</th>
						<th colspan="2" width="20%" style="text-align: center;">操作</th>
					</tr>
				</thead>
				<tbody>
					<#if repeatCategorys??>
						<#list repeatCategorys?keys as key>
							<#list repeatCategorys[key] as category>
								<tr id="${key}_${category_index}">
									<td>${category.title}</td>
									<td>${(category.parentTitle)!''}</td>
									<td><input type="radio" name="${key}_radio" value="${category.id}" /></td>
									<#if category_index==0>
										<td rowspan="${repeatCategorys[key]?size}" style="text-align: center;vertical-align:middle;">
											<button class="btn btn-info" type="button" onclick="mergeC('${key}_radio',this,'${key}',${repeatCategorys[key]?size});">合并</button>
										</td>
									</#if>
								</tr>
							</#list>
							<tr id="${key}_null">
								<td colspan="4">&nbsp;</td>
							</tr>
						</#list>
						<#else>
							<tr>
								<td colspan="4">未查询到结果</td>
							</tr>
					</#if>
				</tbody>
			</table>
		</div>
		<div class="modal-footer ">
			<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
		</div>
	</div>
	<!-- /.modal-content -->
</div>

src/main/resources/templates/category/repeatMark.ftl
<div class="modal-dialog" style="width:90% !important;">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title">重复的书签</h4>
		</div>
		<div class="modal-body">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th width="25%">名称</th>
						<th width="15%">所属分类</th>
						<th colspan="2" width="20%" style="text-align: center;">操作</th>
					</tr>
				</thead>
				<tbody>
					<#if repeatMarks??>
						<#list repeatMarks?keys as key>
							<#if repeatMarks[key]?size gt 1>
								<#list repeatMarks[key] as mark>
									<tr id="${key}_${mark_index}">
										<td>
											<a href="${mark.href}" target="_blank">${mark.name}</a>
										</td>
										<td>${mark.categoryName}</td>
										<td><input type="radio" name="${key}_radio" value="${mark.id}" /></td>
										<#if mark_index==0>
											<td rowspan="${repeatMarks[key]?size}" style="text-align: center;vertical-align:middle;">
												<button class="btn btn-info" type="button" onclick="removeM('${key}_radio',this,'${key}',${repeatMarks[key]?size});">保留</button>
											</td>
										</#if>
									</tr>
								</#list>
								<tr id="${key}_null">
									<td colspan="4"></td>
								</tr>
							</#if>
						</#list>
						<#else>
							<tr>
								<td colspan="4">未查询到结果</td>
							</tr>
					</#if>
				</tbody>
			</table>
		</div>
		<div class="modal-footer ">
			<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
		</div>
	</div>
	<!-- /.modal-content -->
</div>

src/main/resources/templates/category/upload.ftl
<div class="modal fade" id="importMark" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" style="width:70% !important;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">从html导入书签</h4>
			</div>
			<div class="modal-body">
				<form enctype="multipart/form-data">
					<input id="file-0a" name="file" class="file" type="file" />
					<div id="kv-error-1" class="alert alert-warning fade in" style="margin-top:10px;display:none"></div>
					<div id="kv-success-1" class="alert alert-success fade in" style="margin-top:10px;display:none"></div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
</div>