src/main/java/com/control/back/halo/stock/cache/entity/BaseEntity.java
package com.control.back.halo.stock.cache.entity;

import java.io.Serializable;

public abstract class BaseEntity<K> implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1848381224476322373L;

	public abstract K getId();

}

src/main/resources/templates/authorization/login.ftl
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">

    <title>登录</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">
</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">haloSys</h1>
            </div>
            <h3>欢迎使用 halo.System</h3>

            <form class="m-t" role="form" method="post" action="/login/submit.htm">
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="用户名" required>
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="密码" required>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>
     <!--            <p class="text-muted text-center"> 
                	<a href="login.html#"><small>忘记密码了？</small></a> | <a href="register.html">注册一个新账号</a>
                </p> -->
            </form>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/js/jquery.min.js?v=2.1.4"></script>
    <script src="/js/bootstrap.min.js?v=3.4.0"></script>
</body>
</html>

src/main/resources/templates/authorization/register.ftl
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="renderer" content="webkit">

    <title>注册</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link href="/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
    <link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">
    <link href="/css/style.css?v=4.1.0" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">haloSys</h1>

            </div>
            <h3>欢迎注册 halo.System</h3>
            <p>创建一个halo.System新账户</p>
            <form class="m-t" role="form" action="login.html">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入用户名" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="请输入密码" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="请再次输入密码" required="">
                </div>
                 <div class="form-group text-left">
                    <div class="checkbox i-checks">
                        <label class="no-padding">
                            <input type="checkbox"><i></i> 我同意注册协议</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">注 册</button>

                <p class="text-muted text-center"><small>已经有账户了？</small><a href="login.html">点此登录</a>
                </p>

            </form>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/js/jquery.min.js?v=2.1.4"></script>
    <script src="/js/bootstrap.min.js?v=3.4.0"></script>
    <!-- iCheck -->
    <script src="/js/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
</body>
</html>

src/main/resources/templates/authorization/roleIndex.ftl
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<title>角色授权</title>
<link href="/css/bootstrap.min.css?v=3.3.6"
	rel="stylesheet">
<link href="/css/font-awesome.min.css?v=4.4.0"
	rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0" rel="stylesheet">
<link
	href="//cdn.bootcss.com/zTree.v3/3.5.24/css/zTreeStyle/zTreeStyle.css"
	rel="stylesheet">
<link href="/css/plugins/sweetalert/sweetalert.css"
	rel="stylesheet">

<script>
	var _roleId = "${role.id}";
</script>
</head>

<body class="gray-bg">
	<div class="row wrapper border-bottom white-bg page-heading">
		<div class="col-lg-10">
			<h2>角色权限管理</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">主页</a></li>
				<li><a href="/role/index.html">角色管理</a></li>
				<li><a>角色权限管理</a></li>
			</ol>
		</div>
		<div class="col-lg-2"></div>
	</div>

	<div class="wrapper wrapper-content animated fadeInRight">
		<div class="row">
			<div class="col-md-3">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5>菜单目录</h5>
					</div>
					<div class="ibox-content">
						<ul id="functionTree" class="ztree"></ul>
					</div>
				</div>
			</div>
			<div class="col-sm-9">
				<div class="ibox">
					<div class="ibox-title">
						<h5>角色信息</h5>
					</div>
					<div class="ibox-content">
						<div class="row">
							<form class="form-horizontal" id="roleOauthForm">
								<div class="form-group">
									<div class="form-group ">
										<label class="col-lg-3 control-label">角色名称：</label>
										<div class="col-lg-8">
											<span type="text" class="form-control">${role.name}</span>
										</div>
									</div>
								</div>
								<div class="hr-line-dashed"></div>
								<div class="form-group">
									<div class="col-sm-4 col-sm-offset-2">
										<button type="submit" class="btn btn-primary">保存</button>
										<button type="button" class="btn btn-white"
											onclick="history.go(-1);">返回</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script
	src="//cdn.bootcss.com/zTree.v3/3.5.24/js/jquery.ztree.all.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="/js/plugins/sweetalert/sweetalert.min.js"></script>

<script src="/js/pages/role/oauth.js"></script>
<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>
</html>

src/main/resources/templates/authorization/userIndex.ftl
<!doctype html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<title>用户授权</title>
<link href="/css/bootstrap.min.css?v=3.3.6" rel="stylesheet">
<link href="/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<link href="/css/style.css?v=4.1.0" rel="stylesheet">
<link
	href="//cdn.bootcss.com/zTree.v3/3.5.24/css/zTreeStyle/zTreeStyle.css"
	rel="stylesheet">
<link href="/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
<link href="//cdn.bootcss.com/iCheck/1.0.2/skins/all.css"
	rel="stylesheet">

<script>
	var _adminId = "${admin.id}";
</script>
</head>

<body class="gray-bg">
	<div class="row wrapper border-bottom white-bg page-heading">
		<div class="col-lg-10">
			<h2>用户权限管理</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">主页</a></li>
				<li><a href="/admin/index.html">用户管理</a></li>
				<li><a>用户权限管理</a></li>
			</ol>
		</div>
		<div class="col-lg-2"></div>
	</div>

	<div class="wrapper wrapper-content animated fadeInRight">
		<div class="row">
			<div class="ibox">
				<div class="ibox-title">
					<h5>用户权限信息</h5>
				</div>
				<div class="ibox-content">
					<div class="row">
						<form class="form-horizontal" action="/admin/oauthsubmit"
							method="post" id="adminOauthForm">
							<input type="hidden" value="${admin.id}" name="id" />
							<div class="form-group">
								<div class="form-group ">
									<label class="col-lg-3 control-label">用户名称：</label>
									<div class="col-lg-8">
										<span type="text" class="form-control">${admin.user.username}</span>
									</div>
								</div>
							</div>
							<div class="hr-line-dashed"></div>
							<div class="form-group">
								<div class="form-group ">
									<label class="col-lg-3 control-label">角色选择：</label>
									<div class="col-lg-8">
										<#list roles as role> 
											<label class="radio-inline i-checks"> 
												<input type="checkbox" value="${role.id}" 
												<#list admin.roles as r>
													<#if r.id == role.id>
														checked
													</#if>
												</#list>
												 name="roleIds"> 
												<i></i> ${role.name}
											</label> 
										</#list>
									</div>
								</div>
							</div>
							<div class="hr-line-dashed"></div>
							<div class="form-group">
								<div class="col-sm-4 col-sm-offset-2">
									<button type="submit" class="btn btn-primary">保存</button>
									<button type="button" class="btn btn-white"
										onclick="history.go(-1);">返回</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script type="text/javascript"
	src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
<script
	src="//cdn.bootcss.com/zTree.v3/3.5.24/js/jquery.ztree.all.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
<script src="/js/plugins/sweetalert/sweetalert.min.js"></script>
<script src="//cdn.bootcss.com/iCheck/1.0.2/icheck.min.js"></script>
<script src="/js/pages/admin/oauth.js"></script>
<!-- 第三方插件 -->
<script src="/js/plugins/pace/pace.min.js"></script>
</html>